"""Readability by nesting (PLAN.md D13).

A sheet that renders hundreds of nodes is not a map, it is a wall. The tool
already had every piece needed to avoid that — `group` nodes, `expands`, nested
subcharts and double-click drill-in — and the first SpaceAGORA map used none of
them past two levels. This step makes nesting mandatory and mechanical:

* any chart whose rendered node count exceeds `max_nodes_per_sheet` is
  partitioned into macro blocks, one `group` node each;
* every block expands into a generated nested sheet holding its members;
* the parent renders the blocks with the members' edges lifted onto them;
* nested sheets are clustered again until every sheet is readable.

Clustering follows the code's own structure rather than a force layout, so it
is deterministic and reads left-to-right like the rest of the map:

    directory  ->  file  ->  symbol-name prefix (for a file with many symbols)

Group *nodes* are owned by module charts and are the only new prose obligation
(V12 applies at the symbol floor). Workflow views never mint groups; they reuse
the module hierarchy so the same block opens the whole file from a module sheet
and only the workflow's members from a workflow sheet.

Everything here is regenerated on every compile. A generated chart carries
`provenance.generated_by = "cluster"`; hand edits to it will not survive.
"""

from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path

from .model import Chart, Node, Socket
from .scaffold import _id_fragment
from .workspace import Workspace

GROUP_PREFIX = "grp."
GENERATED_BY = "cluster"

GROUP_IN = "members_in"
GROUP_OUT = "members_out"

GROUP_SOCKETS_IN = (
    Socket(id=GROUP_IN, type="call", units="n/a", required=False,
           description="Calls into any member of this block from outside it."),
)
GROUP_SOCKETS_OUT = (
    Socket(id=GROUP_OUT, type="call", units="n/a",
           description="Calls from any member of this block to nodes outside it."),
)

DOC_TEMPLATE = """---
{frontmatter}---

# {label}

## Purpose

## Design & Implementation

## Interface (ICD)
<!-- vulcan:icd:begin -->
<!-- vulcan:icd:end -->

## Connections
<!-- vulcan:connections:begin -->
<!-- vulcan:connections:end -->

## Limitations

## Provenance
Macro block generated by `vulcan compile` (D13) from `{key}`; groups {count} nodes.
Its members are listed in chart `{chart}`.
"""


@dataclass(slots=True)
class ClusterPlan:
    key: str            # what the block stands for: a dir, a file, or "file#prefix"
    label: str
    members: list[str]  # node ids, sorted


@dataclass(slots=True)
class ClusterResult:
    charts_added: list[Chart] = field(default_factory=list)
    charts_removed: list[Chart] = field(default_factory=list)
    groups_added: list[Node] = field(default_factory=list)
    docs_to_scaffold: dict[Path, str] = field(default_factory=dict)
    memberships_changed: int = 0

    @property
    def changed(self) -> bool:
        return bool(self.charts_added or self.charts_removed or self.groups_added
                    or self.memberships_changed)


# ---------------------------------------------------------------- ids

def group_id(key: str) -> str:
    """`src/gnc/control` -> `grp.src_gnc_control`; `a/b.jl#_rhs` -> `grp.a_b_jl__rhs`.

    The extension is kept: a file and a directory of the same name (`x.jl`
    beside `x/`, the Julia convention) are different blocks.
    """
    path, _, prefix = key.partition("#")
    frag = "_".join(_id_fragment(p) for p in path.split("/") if p)
    if prefix:
        frag += "_" + _id_fragment(prefix.strip("_") or "misc")
    return GROUP_PREFIX + frag


def nested_chart_id(root: str, gid: str) -> str:
    """`root` is the top-level chart the nesting hangs off (module or workflow).

    Group ids are unique map-wide, so `<root>-<group>` is unique however deep
    the block sits, and stays short.
    """
    frag = gid[len(GROUP_PREFIX):].replace("_", "-").strip("-")
    while "--" in frag:
        frag = frag.replace("--", "-")
    if frag.startswith("src-"):
        frag = frag[4:]
    return f"{root}-{frag}"


def _label(key: str) -> str:
    """Path relative to the source root, so two `robotics/` blocks in different
    modules are distinguishable on a workflow sheet."""
    path, _, prefix = key.partition("#")
    shown = path[4:] if path.startswith("src/") else path
    name = shown.rsplit("/", 1)[-1]
    if prefix == "_small":
        return f"{shown}/ (small files)"
    if prefix:
        return f"{shown} · {prefix}*"
    return shown if "." in name else f"{shown}/"


# ---------------------------------------------------------------- planning

def _common_dir(files: list[str]) -> str:
    parts = [f.split("/")[:-1] for f in files]
    common: list[str] = []
    for column in zip(*parts):
        if all(c == column[0] for c in column):
            common.append(column[0])
        else:
            break
    return "/".join(common)


def _prefix_token(name: str) -> str:
    core = name.lstrip("_!")
    tok = core.split("_", 1)[0] if "_" in core else core
    return ("_" if name.startswith("_") else "") + tok.lower()


def plan_clusters(
    symbols: list[Node], threshold: int, min_group: int
) -> list[ClusterPlan] | None:
    """Partition `symbols` into blocks, or None when no clustering is needed/possible.

    Symbols must all carry `source.file`. Walks down the directory tree until a
    level with more than one child, then groups by that child; a single file
    with too many symbols is split by leading name token instead.
    """
    if len(symbols) <= threshold:
        return None
    files = sorted({n.source.file for n in symbols if n.source.file})
    if not files:
        return None

    base = _common_dir(files)
    groups: dict[str, list[Node]]
    while True:
        depth = len(base.split("/")) if base else 0
        groups = defaultdict(list)
        for n in symbols:
            parts = n.source.file.split("/")
            child = parts[depth] if len(parts) > depth else parts[-1]
            key = f"{base}/{child}" if base else child
            groups[key].append(n)
        if len(groups) > 1:
            break
        (only,) = groups
        if only.endswith(".jl") or only.endswith(".py") or "." in only.rsplit("/", 1)[-1]:
            # one file — split by symbol-name prefix
            groups = defaultdict(list)
            for n in symbols:
                groups[f"{only}#{_prefix_token(n.label)}"].append(n)
            break
        base = only

    # Fold tiny blocks into one "small" block so the sheet is not a dust cloud.
    small = [k for k, v in groups.items() if len(v) < min_group]
    if len(small) > 1:
        head = base if base else "."
        merged_key = f"{head}#_small" if "#" not in small[0] else f"{small[0].split('#')[0]}#_small"
        merged: list[Node] = []
        for k in small:
            merged.extend(groups.pop(k))
        groups[merged_key] = merged
    if len(groups) <= 1:
        return None
    return [
        ClusterPlan(key=k, label=_label(k), members=sorted(n.id for n in groups[k]))
        for k in sorted(groups)
    ]


# ---------------------------------------------------------------- application

def _chart_by_id(ws: Workspace) -> dict[str, Chart]:
    return {c.chart_id: c for c in ws.charts}


def _rendered_symbols(chart: Chart, index: dict[str, Node]) -> list[Node]:
    """The symbols a chart is responsible for partitioning.

    A module chart owns its `local_nodes`; members it borrows from other
    modules are context (a cross-module callee) and stay visible as they are.
    A generated nested chart owns nothing and partitions its members.
    """
    out: list[Node] = []
    if chart.group:
        for nid in chart.member_nodes:
            n = index.get(nid)
            if n is not None:
                out.append(n)
    else:
        out.extend(chart.local_nodes)
    return [n for n in out if n.kind != "group" and n.source.file]


def _children(ws: Workspace, parent: str) -> list[Chart]:
    return [c for c in ws.charts if c.derives_from == parent and c.group]


def _make_group_node(plan: ClusterPlan, gid: str, owner_chart: str, expands: str | None) -> Node:
    # `expands` follows the existing convention: the coarser node this one is
    # part of the expansion of (the owning module), not a chart id. Which sheet
    # a block opens is recorded on the generated chart (`derives_from`,`group`).
    return Node(
        id=gid,
        label=plan.label,
        kind="group",
        doc=f"nodes/{owner_chart}/{gid[len(GROUP_PREFIX):]}.md",
        inputs=GROUP_SOCKETS_IN,
        outputs=GROUP_SOCKETS_OUT,
        expands=expands,
        tags=("cluster",),
        origin="agent",
    )


def _render_doc(node: Node, plan: ClusterPlan, nested: str, owner_chart: str) -> str:
    import yaml

    meta = {
        "id": node.id,
        "label": node.label,
        "kind": "group",
        "inputs": [s.to_dict() for s in node.inputs],
        "outputs": [s.to_dict() for s in node.outputs],
        "expands": node.expands,
        "tags": ["cluster"],
        "charts": [owner_chart],
        "origin": "agent",
    }
    fm = yaml.safe_dump(meta, sort_keys=False, allow_unicode=True)
    return DOC_TEMPLATE.format(
        frontmatter=fm, label=node.label, key=plan.key, count=len(plan.members), chart=nested
    )


def _make_nested_chart(
    parent: Chart, gid: str, plan: ClusterPlan, members: list[str], mind_dir: Path, root: str
) -> Chart:
    cid = nested_chart_id(root, gid)
    return Chart(
        chart_id=cid,
        chart_kind="sub",
        title=f"{plan.label} ({root})",
        region=parent.region,
        derives_from=parent.chart_id,
        provenance={"generated_by": GENERATED_BY, "cluster_key": plan.key},
        member_nodes=list(members),
        group=gid,
        path=mind_dir / f"{cid}.graph.json",
    )


def _cluster_module_chart(
    ws: Workspace, chart: Chart, index: dict[str, Node], result: ClusterResult,
    threshold: int, min_group: int, owner_chart: str,
) -> None:
    """Cluster one module-side chart (a subchart or a generated nested one)."""
    symbols = _rendered_symbols(chart, index)
    plans = plan_clusters(symbols, threshold, min_group) or []
    wanted = {group_id(p.key): p for p in plans}

    existing = {c.group: c for c in _children(ws, chart.chart_id)}
    # Charts for blocks that no longer exist.
    for gid, child in existing.items():
        if gid not in wanted and child.is_generated:
            ws.charts.remove(child)
            result.charts_removed.append(child)

    owner = ws.chart(owner_chart)
    owned_groups = {n.id: n for n in (owner.local_nodes if owner else [])}
    module_id = next((n.expands for n in (owner.local_nodes if owner else []) if n.expands), None)
    for gid, plan in wanted.items():
        nested_id = nested_chart_id(owner_chart, gid)
        node = owned_groups.get(gid) or index.get(gid)
        if node is None:
            node = _make_group_node(plan, gid, owner_chart, module_id)
            if owner is not None:
                owner.local_nodes.append(node)
                owner.local_nodes.sort(key=lambda n: n.id)
            index[gid] = node
            result.groups_added.append(node)
            result.docs_to_scaffold[ws.mind.root / node.doc] = _render_doc(node, plan, nested_id, owner_chart)

        child = existing.get(gid)
        if child is None:
            child = _make_nested_chart(chart, gid, plan, plan.members, ws.mind.subcharts_dir, owner_chart)
            ws.charts.append(child)
            result.charts_added.append(child)
        elif child.member_nodes != plan.members:
            child.member_nodes = list(plan.members)
            result.memberships_changed += 1
        # Recurse: a block may still be too big.
        _cluster_module_chart(ws, child, index, result, threshold, min_group, owner_chart)


def _module_hierarchy(ws: Workspace) -> dict[str, list[tuple[str, str]]]:
    """symbol id -> [(group id, module-side nested chart id), ...] coarse to fine."""
    out: dict[str, list[tuple[str, str]]] = defaultdict(list)

    def walk(chart: Chart, chain: list[tuple[str, str]]) -> None:
        for child in _children(ws, chart.chart_id):
            link = chain + [(child.group or "", child.chart_id)]
            for nid in child.member_nodes:
                out[nid] = link
            walk(child, link)

    for chart in ws.charts:
        if chart.is_master or chart.is_workflow or chart.group:
            continue
        walk(chart, [])
    return out


def _cluster_workflow_chart(
    ws: Workspace, chart: Chart, index: dict[str, Node], hierarchy: dict[str, list[tuple[str, str]]],
    result: ClusterResult, threshold: int, level: int, root: str,
) -> None:
    """Project a workflow sheet onto the module hierarchy at `level` deep."""
    members = [nid for nid in chart.member_nodes if nid in index]
    symbols = [index[nid] for nid in members if index[nid].kind != "group"]
    existing = {c.group: c for c in _children(ws, chart.chart_id)}

    blocks: dict[str, list[str]] = defaultdict(list)
    if len(symbols) > threshold:
        for n in symbols:
            chain = hierarchy.get(n.id, [])
            if len(chain) > level:
                blocks[chain[level][0]].append(n.id)
    # Only cluster when it actually helps; a projection that leaves the sheet
    # over threshold is reported by V20 rather than papered over.
    if len(blocks) <= 1:
        blocks = {}

    for gid, child in existing.items():
        if gid not in blocks and child.is_generated:
            ws.charts.remove(child)
            result.charts_removed.append(child)

    for gid in sorted(blocks):
        mem = sorted(blocks[gid])
        child = existing.get(gid)
        gnode = index.get(gid)
        label = gnode.label if gnode else gid
        if child is None:
            plan = ClusterPlan(key=gid, label=label, members=mem)
            child = _make_nested_chart(chart, gid, plan, mem, ws.mind.subcharts_dir, root)
            ws.charts.append(child)
            result.charts_added.append(child)
        elif child.member_nodes != mem:
            child.member_nodes = mem
            result.memberships_changed += 1
        _cluster_workflow_chart(ws, child, index, hierarchy, result, threshold, level + 1, root)


def apply(ws: Workspace) -> ClusterResult:
    """Bring the workspace's charts to the clustered state D13 requires (in memory)."""
    threshold = ws.config.max_nodes_per_sheet
    min_group = ws.config.cluster_min_group
    result = ClusterResult()
    index = {n.id: n for c in ws.charts for n in c.all_nodes()}

    # Module side first: these own the group nodes.
    for chart in [c for c in ws.charts if not c.is_master and not c.is_workflow and not c.group]:
        _cluster_module_chart(ws, chart, index, result, threshold, min_group, chart.chart_id)

    hierarchy = _module_hierarchy(ws)
    for chart in [c for c in ws.charts if c.is_workflow]:
        _cluster_workflow_chart(ws, chart, index, hierarchy, result, threshold, 0, chart.chart_id)
    return result
