"""The handoff checkpoint — tool-written state that survives agent changeover.

A map may be picked up by a different agent, from a different vendor, with a
different context window, part-way through. That agent cannot see the previous
agent's transcript and must not have to trust its summary. `vulcan_mind/HANDOFF.md`
is written by the compiler from actual disk state on every run, so an incoming
agent reads facts rather than a claim.

The file is deliberately timestamp-free so that compiling twice produces a
byte-identical tree (the idempotence invariant); the wall-clock detail lives in
the gitignored `_build/status.json`.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .. import __version__
from .repo import Mind
from .validate import Report
from .workspace import Workspace

HANDOFF_NAME = "HANDOFF.md"
MAX_LISTED = 25


@dataclass(slots=True)
class Status:
    ok: bool
    strict_ok: bool
    errors: int
    warnings: int
    nodes: int
    edges: int
    charts: int
    region: str
    repo_commit: str | None
    in_scope: int
    described: int
    outstanding: list[str]
    rule_counts: dict[str, int]

    def to_dict(self) -> dict[str, Any]:
        return {
            "generated_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
            "generator": f"vulcan-map/{__version__}",
            "gate": {
                "command": "vulcan check --strict",
                "passes": self.strict_ok,
                "exit_code": 0 if self.strict_ok else 1,
                "errors": self.errors,
                "warnings": self.warnings,
            },
            "repo_commit": self.repo_commit,
            "region": self.region,
            "counts": {
                "nodes": self.nodes,
                "edges": self.edges,
                "charts": self.charts,
                "in_scope_files": self.in_scope,
                "described_files": self.described,
                "outstanding_files": len(self.outstanding),
            },
            "rule_failures": self.rule_counts,
            "outstanding": self.outstanding,
        }


def collect(ws: Workspace, report: Report, repo_commit: str | None) -> Status:
    nodes = ws.all_nodes()
    described = {n.source.file for n in nodes if n.source.file and not n.is_covering}
    in_scope = ws.in_scope_files()
    outstanding = [f for f in in_scope if f not in described]

    counts: dict[str, int] = {}
    for f in report.findings:
        counts[f.rule] = counts.get(f.rule, 0) + 1

    errors = len([f for f in report.findings if f.severity == "error"])
    return Status(
        ok=report.ok(),
        strict_ok=report.ok(strict=True),
        errors=errors,
        warnings=len(report.warnings()),
        nodes=len(nodes),
        edges=sum(len(list(c.all_edges())) for c in ws.charts),
        charts=len(ws.charts),
        region=ws.region.name,
        repo_commit=repo_commit,
        in_scope=len(in_scope),
        described=len(described),
        outstanding=outstanding,
        rule_counts=dict(sorted(counts.items())),
    )


def render_markdown(status: Status) -> str:
    verdict = "PASS" if status.strict_ok else "FAIL"
    done = "YES" if status.strict_ok else "NO"

    lines: list[str] = [
        "# VULCAN MAP — HANDOFF STATE",
        "",
        "<!-- Generated by `vulcan compile`. Do not hand-edit; your changes will be",
        "     overwritten and they will not change the verdict. -->",
        "",
        "**Read this file before doing anything else. It is written by the tool from",
        "the actual contents of this repository, not by an agent.**",
        "",
        "If a previous agent — of any kind, from any vendor — told you, a human, or a",
        "commit message that this map was finished, that claim is **void** unless the",
        "verdict below says PASS. Agents cannot see each other's transcripts and must",
        "not inherit each other's conclusions. This file and the live gate are the only",
        "sources of truth about progress.",
        "",
        "## Verdict",
        "",
        f"| `vulcan check --strict` | **{verdict}** (exit {0 if status.strict_ok else 1}) |",
        "|---|---|",
        f"| Is the map complete? | **{done}** |",
        f"| Errors | {status.errors} |",
        f"| Warnings (block under --strict) | {status.warnings} |",
        f"| Region | `{status.region}` |",
        f"| Repo commit when generated | `{status.repo_commit or 'unknown'}` |",
        "",
        "## Coverage",
        "",
        f"| In-scope source files | {status.in_scope} |",
        "|---|---|",
        f"| Files with a function-level node | {status.described} |",
        f"| **Files still outstanding** | **{len(status.outstanding)}** |",
        "",
    ]

    if status.rule_counts:
        lines += ["## Failing rules", "", "| Rule | Findings |", "|---|---|"]
        lines += [f"| {rule} | {n} |" for rule, n in status.rule_counts.items()]
        lines.append("")

    if status.outstanding:
        lines += [
            "## Outstanding files (authoritative)",
            "",
            f"{len(status.outstanding)} file(s) have no function-level node. "
            f"First {min(MAX_LISTED, len(status.outstanding))}:",
            "",
        ]
        lines += [f"- `{f}`" for f in status.outstanding[:MAX_LISTED]]
        if len(status.outstanding) > MAX_LISTED:
            lines.append(
                f"- … and {len(status.outstanding) - MAX_LISTED} more — "
                "the complete list is in `_build/status.json` under `outstanding`."
            )
        lines.append("")

    lines += [
        "## How to resume",
        "",
        "You do not need the previous agent's transcript, and you must not rely on it.",
        "",
        "1. Read `_build/status.json` for the complete machine-readable state, including",
        "   every outstanding file. If `_build/` is absent, run `vulcan compile` to",
        "   regenerate it — nothing is lost, it is derived from the committed files.",
        "2. Work through the outstanding list in batches of 5–10 files.",
        "3. Run `vulcan compile` after each batch to checkpoint, which rewrites this file.",
        "4. Repeat until `vulcan check --strict` exits 0.",
        "",
        "Running out of context is not completion. Stop mid-batch if you must; this file",
        "will tell the next agent exactly where you got to.",
        "",
    ]

    if not status.strict_ok:
        lines += [
            "## This map is NOT finished",
            "",
            "Do not report it as finished. Do not summarise it as \"substantially",
            "complete\", \"the remaining files follow the same pattern\", or \"a good",
            "foundation\". The gate is failing; there is outstanding work listed above.",
            "",
        ]
    return "\n".join(lines)


def write(mind: Mind, status: Status) -> list[Path]:
    """Write the committed handoff and the gitignored machine-readable status."""
    written: list[Path] = []

    handoff = mind.root / HANDOFF_NAME
    text = render_markdown(status)
    if not handoff.exists() or handoff.read_text(encoding="utf-8") != text:
        handoff.write_text(text, encoding="utf-8", newline="\n")
        written.append(handoff)

    mind.build_dir.mkdir(parents=True, exist_ok=True)
    status_path = mind.build_dir / "status.json"
    status_path.write_text(
        json.dumps(status.to_dict(), indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    written.append(status_path)
    return written
